### ISSUE TITLE
computer-programming_page links"

### ISSUE THREAD

**Issue by gayatripurigilla** [virtual-labs/computer-programming-responsive-iiith#129]
# Defect descriptionhomepage-link needed to be linked to the logo and "explore labs" link is not needed.# actual result1. click on "computer-programming lab" link.2. "explore labs" link on the page is not needed as appears in the Screenshot as it is the same as the home page.3. the logo of "virtual labs" is not linked to the iiit hyd virtual lab's home page.Screenshot:![image](https://gitlab.com/rashmigofficial/virtual-labs-internship-rashmig/uploads/8c47dc416a44e1261467bcf0fc54195b/image.png)# expected result1. "explore labs" link can be removed or the "home" link shall be improved to introduction and prerequisites for the lab.2. the logo of virtual labs at the top right corner must be linked to iiit hyd virtual lab's home page.

**Comment by adityagoda24** [comment]
commit id: 8bb7fec
The logos and the explore labs are fixed

**Comment by Rajadattu** [comment]
Valid fix @adityagoda24

**Comment by Sumaid** [comment]
@adityagoda24 The second image seems to be slightly off. 
![cutmypic](https://user-images.githubusercontent.com/32260836/42050906-ebf04f06-7b27-11e8-88aa-e63669529ec0.png)

**Comment by adityagoda24** [comment]
I think I did not touch the other part of the code . I only attached  links .

**Comment by Sumaid** [comment]
@adityagoda24, Sometimes, just adding links can cause issues with layout - and I can see this problem in layout only in yours. This issue is still not fixed.

**Comment by Yerram-Sai-Rachana** [comment]
My commit id: 65ba591

**Comment by Mani082** [comment]
You have only fixed links @Yerram-Sai-Rachana. But the images are misplaced. Not a right fix.

**Comment by Mani082** [comment]
Commit ids:
4b647ce - Added appropriate links to the images
0d3357e - Changed CSS styling so that both the images come side by side(their appropriate positions).

**Comment by koushik1298** [comment]
Valid @Mani082

**Comment by DevikaBoddu** [comment]
validated @Mani082
